### ISSUE TITLE
unable to start a game

### ISSUE THREAD

**Issue by AlteredCarrot71** [AlteredCarrot71/SpaceTraders#10]
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=SpaceTraders
  StackTrace:
   at SpaceTraders.MapScreen..ctor() in SpaceTraders.Core\MapScreen.xaml.cs:line 47
   at SpaceTraders.SpaceTraders_XamlTypeInfo.XamlTypeInfoProvider.Activate_4_MapScreen() in SpaceTraders.Core\obj\x64\Debug\XamlTypeInfo.g.cs:line 190
   at SpaceTraders.SpaceTraders_XamlTypeInfo.XamlUserType.ActivateInstance() in SpaceTraders.Core\obj\x64\Debug\XamlTypeInfo.g.cs:line 383

**Comment by AlteredCarrot71** [comment]
9b168fd28163aa6785202f2c0a80c312d87628b0 maybe resolve this issue.
